// Generated by tools/prepare_art.py. Do not edit by hand.
//
// Section 67: what shape each piece of the capital is, and where along its
// own width it stands. `foot` is the middle of its lowest row of pixels --
// the near corner of an isometric box, the bottom of a banner pole -- which
// is the point the compositor lines pieces up by.
export interface PalacePieceArt {
  w: number;
  h: number;
  foot: number;
  /** Share of its own frame the piece filled before trimming. */
  frame: number;
}

export const PALACE_ART: Record<string, PalacePieceArt> = {
  'human-banners-1': { w: 93, h: 128, foot: 0.392, frame: 1.000 },
  'human-banners-2': { w: 113, h: 128, foot: 0.500, frame: 1.000 },
  'human-banners-3': { w: 113, h: 128, foot: 0.500, frame: 1.000 },
  'human-base': { w: 128, h: 99, foot: 0.449, frame: 1.000 },
  'human-gate-1': { w: 113, h: 128, foot: 0.500, frame: 1.000 },
  'human-gate-2': { w: 121, h: 128, foot: 0.822, frame: 1.000 },
  'human-gate-3': { w: 113, h: 128, foot: 0.779, frame: 1.000 },
  'human-grounds-1': { w: 128, h: 94, foot: 0.496, frame: 1.000 },
  'human-grounds-2': { w: 128, h: 108, foot: 0.496, frame: 1.000 },
  'human-grounds-3': { w: 128, h: 99, foot: 0.668, frame: 1.000 },
  'human-tower-1': { w: 104, h: 128, foot: 0.495, frame: 1.000 },
  'human-tower-2': { w: 78, h: 128, foot: 0.494, frame: 1.000 },
  'human-tower-3': { w: 63, h: 128, foot: 0.492, frame: 1.000 },
  'human-wing-1': { w: 121, h: 128, foot: 0.463, frame: 1.000 },
  'human-wing-2': { w: 121, h: 128, foot: 0.463, frame: 1.000 },
  'human-wing-3': { w: 124, h: 128, foot: 0.472, frame: 1.000 },
  'orc-banners-1': { w: 72, h: 128, foot: 0.507, frame: 1.000 },
  'orc-banners-2': { w: 102, h: 128, foot: 0.275, frame: 1.000 },
  'orc-banners-3': { w: 101, h: 128, foot: 0.272, frame: 1.000 },
  'orc-base': { w: 128, h: 117, foot: 0.496, frame: 1.000 },
  'orc-gate-1': { w: 113, h: 128, foot: 0.714, frame: 1.000 },
  'orc-gate-2': { w: 113, h: 128, foot: 0.714, frame: 1.000 },
  'orc-gate-3': { w: 113, h: 128, foot: 0.714, frame: 1.000 },
  'orc-grounds-1': { w: 126, h: 128, foot: 0.494, frame: 1.000 },
  'orc-grounds-2': { w: 127, h: 128, foot: 0.487, frame: 1.000 },
  'orc-grounds-3': { w: 127, h: 128, foot: 0.491, frame: 1.000 },
  'orc-tower-1': { w: 105, h: 128, foot: 0.495, frame: 1.000 },
  'orc-tower-2': { w: 104, h: 128, foot: 0.495, frame: 1.000 },
  'orc-tower-3': { w: 104, h: 128, foot: 0.495, frame: 1.000 },
  'orc-wing-1': { w: 119, h: 128, foot: 0.454, frame: 1.000 },
  'orc-wing-2': { w: 128, h: 125, foot: 0.504, frame: 1.000 },
  'orc-wing-3': { w: 128, h: 125, foot: 0.504, frame: 1.000 },
};
